### ISSUE TITLE
Add Kazakh Arabic support

### ISSUE THREAD

**Issue by madmansnest** [silnrsi/font-awami#9]
Kazakh is also written using Arabic script by Kazakhs living in China, Iran and Afghanistan, it would be great if it were also supported.

It is necessary to add support for the following letters:
initial/medial/final/isolated
ڭـ
initial/isolated
ٶ‎
ٷ‎
ٸـ‎

**Comment by LornaSIL** [comment]
In the soon-to-be released version of Awami Nastaliq we have added the U+06AD character.

We have NOT added U+0676, U+0677, and U+0678 because the use of these characters is discouraged. See the Unicode codecharts annotation:

> Use of these characters is discouraged. They were encoded for
> Kazakh digraphs, but their decompositions do not reflect the
> preferred order of representation. Accordingly, the
> representation of these Kazakh digraphs should instead use
> the preferred two-character spellings with the correct order of
> elements.

Instead, we do support the Unicode recommended characters for those:

> U+0674 U+0648
> U+0674 U+06C7
> U+0674 U+0649

ڭـ
